ingress:
  name: lottery-ingress
  host: basselanthony.com

services:
  nodejs:
    name: node-js-service
    containerName: node-js-container
    port: 80
    replicaCount: 3
    image:
      repository: basselsaade/basselanthony:bei
      tag: latest
  reactjs:
    name: react-js-service
    containerName: react-js-container
    port: 80
    replicaCount: 3
    image:
      repository: basselsaade/basselanthony:feb
      tag: latest